apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ghost-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ghost
          servicePort: http
